### ISSUE TITLE
Project structure / Kanban board setup.

### ISSUE THREAD

**Issue by Bavon101** [Bavon101/space-travelers-hub#25]
Hello,

- We have managed to set up the [project](https://github.com/Bavon101/space-travelers-hub/projects/1) as per the requirements.
- We are a team of two [@Bavon101 , @Thermiee ].

**Comment by mmsesay** [comment]
Hi @Bavon101 & @Thermiee, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
